In [10]:
import numpy as np

def sigmoid(x): return 1 / (1+np.exp(-x))
def sigmoid_deriv(x): return x * (1-x)

In [11]:
training_inputs = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])

In [12]:
training_outputs = np.array([[0,1,1,0]]).T
np.random.seed(1)

In [13]:
synaptic_weights = 2 * np.random.random((3,1)) - 1
print("Random starting synaptic weight: ")
print(synaptic_weights)

Random starting synaptic weight: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [20]:
for iteration in range(200000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - outputs
    adjustments = error * sigmoid_deriv(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

In [21]:
print("synaptic weights post training: ")
print(synaptic_weights)

synaptic weights post training: 
[[12.80209005]
 [-0.20386947]
 [-6.19740982]]


In [22]:
print("output: ")
print(outputs)

output: 
[[0.00203057]
 [0.99834254]
 [0.99864781]
 [0.00165669]]
